name: CI

on:
  push:
    branches:
      - master
  pull_request:
  # schedule:
  #   - cron: "0 23 * * 6"

jobs:
  # test:
  #   strategy:
  #     matrix:
  #       PLATFORM:
  #         - "ubuntu-latest"
  #         # - "macos-latest"
  #         # - "windows-latest"
  #       NODE:
  #         # - "13"
  #         - "12"
  #         # - "10"
  #       # exclude:
  #       #   - PLATFORM: "macos-latest"
  #       #     NODE: "12"

  #   name: Test on node ${{ matrix.NODE }} and ${{ matrix.PLATFORM }}
  #   runs-on: ${{ matrix.PLATFORM }}
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@master

  #     - name: Setup Node.js
  #       uses: actions/setup-node@master
  #       with:
  #         node-version: ${{ matrix.NODE }}

  #     - name: Install Dependencies
  #       run: yarn

  #     - name: Run Test
  #       run: yarn test-coverage

  #     - name: Upload Coverage Parallel
  #       uses: coverallsapp/github-action@master
  #       if: success()
  #       with:
  #         github-token: ${{ secrets.GITHUB_TOKEN }}
  #         parallel: true

  #     - name: Upload Coverage Finished
  #       uses: coverallsapp/github-action@master
  #       if: success()
  #       with:
  #         github-token: ${{ secrets.GITHUB_TOKEN }}
  #         parallel-finished: true

  # test-dist:
  #   strategy:
  #     matrix:
  #       PLATFORM:
  #         - "ubuntu-latest"
  #         # - "macos-latest"
  #         # - "windows-latest"
  #       NODE:
  #         # - "13"
  #         - "12"
  #         # - "10"
  #       # exclude:
  #       #   - PLATFORM: "macos-latest"
  #       #     NODE: "12"

  #   name: Test on node ${{ matrix.NODE }} and ${{ matrix.PLATFORM }}
  #   runs-on: ${{ matrix.PLATFORM }}
  #   needs: [build]
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@master

  #     - name: Setup Node.js
  #       uses: actions/setup-node@master
  #       with:
  #         node-version: ${{ matrix.NODE }}

  #     - name: Install Dependencies
  #       run: yarn

  #     - name: Download Artifact
  #       uses: actions/download-artifact@master
  #       with:
  #         name: dist
  #         path: dist

  #     - name: Run Test
  #       run: yarn test-coverage

  #     - name: Upload Coverage Parallel
  #       uses: coverallsapp/github-action@master
  #       if: success()
  #       with:
  #         github-token: ${{ secrets.GITHUB_TOKEN }}
  #         parallel: true

  #     - name: Upload Coverage Finished
  #       uses: coverallsapp/github-action@master
  #       if: success()
  #       with:
  #         github-token: ${{ secrets.GITHUB_TOKEN }}
  #         parallel-finished: true

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: "12"

      - name: Install Dependencies
        run: yarn

      - name: Run Lint
        run: yarn lint

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: "12"

      - name: Install Dependencies
        run: yarn

      - name: Build Package
        run: yarn build

      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
