name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    strategy:
      fail-fast: false
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: 10.x

      - name: Install Dependencies
        run: yarn

      - name: Run Lint
        run: yarn lint

  test:
    strategy:
      fail-fast: false
      matrix:
        PLATFORM:
          - ubuntu-latest
          # - macos-latest
          # - windows-latest
        NODE:
          # - 12.x
          - 10.x
        # exclude:
        #   - PLATFORM: macos-latest
        #     NODE: 12.x
        #   - PLATFORM: windows-latest
        #     NODE: 12.x

    name: Test on node ${{ matrix.NODE }} and ${{ matrix.PLATFORM }}

    runs-on: ${{ matrix.PLATFORM }}

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.NODE }}

      - name: Install Dependencies
        run: yarn

      - name: Build Package
        run: yarn build
      # - name: Run Test
      #   run: yarn test-coverage
      # - name: Upload Coverage
      #   uses: coverallsapp/github-action@master
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
